### ISSUE TITLE
Using the URL reverse in route configurations

### ISSUE THREAD

**Issue by merll** [jrief/django-angular#116]
I find that the new method for URL resolution is a really good idea. It removes a lot of specific code from the templates and makes usage of Django-configured URLs very intuitive.
As `djangoUrl` is a service, it can however not be used directly for configuring AngularJS providers. One example where this would be useful is the `$routeProvider`. For the route paths, using constants seems fine, since the URLs are only used client-side anyway. However, for loading templates via `templateUrl` it would make sense to use Django-defined names.

The `templateUrl` of a route configuration can be implemented as a function, which unfortunately does not support dependency injection. As a workaround, the following constant can be defined in the app module:

```
constant('djUrl', function(name) {
    return function(params) {
        var $injector = angular.injector(['ng.django.urls']);
        return $injector.invoke(['djangoUrl', function(djangoUrl) {
            return djangoUrl.reverse(name, params);
        }]);
    }
})
```

Then `djUrl` can be injected like any other constant, and referenced in the `templateUrl`, e.g.
`templateUrl: djUrl('app:article_template')`. This works, but I am wondering if anyone can think of a better approach.
Making `djangoUrl` a provider would by itself not solve the problem, as the service object is still not available during the config phase. A provider could however include the aforementioned function generator.

**Comment by gabn88** [comment]
I would like to share my thoughts on this. Please note I'm an Angular beginner, so I could be wrong.

I have a Django application that creates my views  (which are my angular templates) *and translates them* for use in my angular frontend. Therefore I need to use django templates which are going through the Django parser and which have an urlpattern in urls.py set up. 

This way, it would be really helpfull if I could use djangoUrl in my app config to define my angular routes. Now I have to use the hardcoded urls, which while not a problem is really cumbersome. Especially because I have all the name's already setup on a different namespace for usage without angular, which I could essentially copy otherwise.

**Comment by cho-is** [comment]
+1

**Comment by adrienbrunet** [comment]
@jkosir I agree with you. The less coupling we have between the back and the front, the better. I'm not fond of a {{djangoUrl}} template method.

Do you think we should implement something or change it?
As it's been almost a year without activity, I'm closing the issue. Feel free to reopen it.

**Comment by jkosir** [comment]
Uhhh, totally forgot about this.

So generally this isn't a issue, but in case you want to use ``djangoUrl`` in ``$routeProvider`` config you can use the posted workaround.  
I suggest we don't change anything. In case there is more activity for this use case we could add something like this workaround or any nicer solution.
