### ISSUE TITLE
Allow NgCRUDView to serialize foreign key relationships

### ISSUE THREAD

**Issue by joelhaasnoot** [jrief/django-angular#138]
It would be very nice to be able to easily serialize relationships in Django models, based on a parameter for NgCRUDView. Mainly I want the Read/GET calls to be able to get a bigger set of data to avoid a large  number of requests for what is essentially a tree of data - for instance when searching.

I've worked around how NgCRUDView is implemented by overriding serialize_queryset() with the following implementation, using the dependency django-preserialize which takes an extra parameter 'related' :
````
 def serialize_queryset(self, queryset):
        """
        Return serialized queryset or single object as python dictionary
        """
        return serialize(queryset, fields=self.get_fields(), related=self.related)
````

**Comment by FabrizioA** [comment]
Hi, I've a similar problem with a ModelForm and a ManyToMany relational field.

I have a Contract model with a manytomany rel "accessories" to Accessory model.
This is my form.py

```python
from djangular.forms import widgets as djangular_widgets

class ContractAdminForm(NgModelFormMixin, NgModelForm):
    form_name = "contract_form"
    scope_prefix = 'contract'

    class Meta:
        model = Contract
        fields = '__all__'
        widgets = {
            'accessories': djangular_widgets.CheckboxSelectMultiple
        }
```

the rendered field looks like this:
```html
<ul ng-form="accessories" class="ng-pristine ng-valid">
<li><label for="id_accessories_0"><input id="id_accessories_0_0" name="accessories.1" ng-model="contract.accessories.1" type="checkbox" value="1" class="ng-pristine ng-untouched ng-valid"> Tom Tom</label></li>
<li><label for="id_accessories_1"><input id="id_accessories_1_1" name="accessories.2" ng-model="contract.accessories.2" type="checkbox" value="2" class="ng-pristine ng-untouched ng-valid"> Seggiolino Bambino</label></li>
</ul>
```

Obviously when this html is rendered, AngularJS return my an error because I instantiated invalid ngModel contract.accessories.1  or   .2 which are the id of related accessory object.

**Comment by adrienbrunet** [comment]
@jrief Do we still want to add support for a better serializer which follows foreignkeys/relationship? It can get pretty complicated and I think it's a bit out of scope for this project. Such customization can be achieved successfully with `django-rest-framework` for example. (Or via a custom serializer) But I don't think we need to support it. NgCRUDView is a helper to get things done quickly and efficiently but it's not robust enough anyway to be extended with more complicated models. I'm closing this issue because of its lacks of activity and because I don't feel it's something we should spent time on. Feel free to reopen it and/or give some directives to achieve it.

**Comment by jrief** [comment]
@adrienbrunet I fully agree with you that for foreign key relations, DRF is best suited. I currently have two projects which combine django-angular and DRF.
