### ISSUE TITLE
Please add example/demo for UpdateView

### ISSUE THREAD

**Issue by nmgeek** [jrief/django-angular#184]
Without an example for the crucial functionality to build a djangular-enabled Django UpdateView I had to figure it out on my own.  It makes sense to me that there should be an example in the demo which shows how to do this so others won't have to figure it out from scratch.

See http://stackoverflow.com/questions/31483408/django-generic-updateview-in-djangular for the appropriate code fragments.  Hopefully I solved the problem correctly.  (It passed my tests.) If not, feel free to fix it.

**Comment by adrienbrunet** [comment]
Well, the solution provided in SO works.
From a personal POV, when using angular, I tend to use directly POST/PUT request on my API and not use a dedicated Django view for each method. The point of using angular (with a SPA for example) is to load dynamically objects into my forms and save them on the go.

I'm closing this due to a lack of activity.

@jrief @jkosir What do you think? Do you want to add an example? (If yes or if you want me to provide one at some point, reopen the issue)
