### ISSUE TITLE
Is Angular 2 already supported?

### ISSUE THREAD

**Issue by feniixx** [jrief/django-angular#219]
I want to develop applycations with angular 2/python, so I'd like to know if this lets me use Django and Angular 2?

**Comment by jkosir** [comment]
No, only Angular 1.x is supported. Angular 2 has a completely different API and syntax so I doubt it will ever be supported in this package, creating a new package with similar functionality for Angular2 seems like better idea.

@jrief @adrienbrunet ... any plans for working with angular2?

**Comment by feniixx** [comment]
Yeah, you're right.

**Comment by jrief** [comment]
Recently I had a look at AngularJS2. This is a completely different framework, although I liked what I saw. Presumably sooner or later I'll change myself, because imho AngualrJS1 is too complicate to program.

That said, it would be better to have another layer of abstraction. Unfortunately Anguar-Forms can't be rendered using the Django template language – its simply too slow. But there are other template languages around which seem to address this problem, for instance [PyTenjin](http://www.kuwata-lab.com/tenjin/pytenjin-users-guide.html), [Mako](http://www.makotemplates.org/) or Jinja2.
Such a template language does not require a lot of features but it must be really fast.

**Comment by radeksvarz** [comment]
Hi,
I was on the ng meetup yesterday. The Angular 2 seams to be getting traction. Now with beta 3 and angular 1.5 bringing some compatibility.

I was advised to already start with Angular 2 for the new app version.

So the main question here: 

 - django-angular - will it support angular 2?

or 

 - is there any other project to tackle it?
