### ISSUE TITLE
Django Channels

### ISSUE THREAD

**Issue by 0nkery** [jrief/django-angular#267]
What do you think about adopting three-way data binding to recent Django Channels package? It would be really convenient. 

django-websocket-redis does basically the same, but (you know) the installation and deploy not so easy. :(

**Comment by jrief** [comment]
This would be a great idea. Unfortunately, channels was not available at the time, so I started with the django-websocket-redis project. Now however, I'm some biased to it :)

But if you want to implement channels instead of ws4redis, please go ahead and create a PR. I currently have no time to implement and no need for it.
