### ISSUE TITLE
 module 'django.forms.widgets' has no attribute 'ChoiceFieldRenderer'

### ISSUE THREAD

**Issue by Fantalic** [jrief/django-angular#299]
\django-angular-master\djng\forms\widgets.py", line 44, in <module>
    class ChoiceFieldRenderer(widgets.ChoiceFieldRenderer):
AttributeError: module 'django.forms.widgets' has no attribute 'ChoiceFieldRenderer'

**Comment by adrienbrunet** [comment]
Hi there Fantalic, this is a fine traceback but could you provide more informations ? How did you get that error ? With which django version ? What did you tried ? If you want us to help you, we need more info... If you can provide a minimum example or better : a failing test, it would be greatly appreciated. otherwise, we can't help you

**Comment by jrief** [comment]
@Fantalic I presume that you are running Django-1.11 with django-angular-0.8.4, which of course is not supported there.

**Comment by Fantalic** [comment]
thanks for answering. but I have to work with yii-react framework now. Maybe I come back to this another time.
