### ISSUE TITLE
MRO issue for NgWidgetMixin, Select

### ISSUE THREAD

**Issue by jameschristopher** [jrief/django-angular#312]
Has anyone else experience an MRO TypeError when using Select widgets ( for django ModelChoiceField) with NgModelForm, and NgModelFormMixin?

This issue seems to have been introduced during https://github.com/jrief/django-angular/commit/0376e8bf5ff438853c8617ffbf625af01c251211 as I do not get an exception when on version 1.0.0.

I'm not to familiar with the code there but would be willing to try and fix with a PR, this exception could also be an implementation error on my part.

**Comment by jrief** [comment]
Yes there is an issue already and will be fixed soon (give me 2 more weeks), or try yourself.

**Comment by jameschristopher** [comment]
Which issue? With a little more context I'll give it a try

**Comment by abs25** [comment]
I have a PR which (should) fix this: #308. @jrief, is there something about that fix you don't like? 

I'm not entirely sure what is causing the underlying issue, as I don't think most forms are rendered twice like my test case does in order to cause the error. Maybe that is what he is looking into.

**Comment by jameschristopher** [comment]
Oh, somehow I missed your PR. I'll close this issue then.
